version: "3.1"
services:
  pdf-backend:
    image: pdf-backend
    restart: always
    ports:
      - 8080:8080
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: singh
      MONGO_INITDB_ROOT_PASSWORD: 12345678
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: singh
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
volumes:
  mongodata:
networks:
  default:
    external:
      name: pdf-network